### ISSUE TITLE
TF計算模組

### ISSUE THREAD

**Issue by zmes50416** [zmes50416/DTG#11]
計算出現在字詞圖型內相同的字詞出現的次數
以raw freqency為計算方式(每出現一次+1)

**Comment by AlianWang** [comment]
finish

**Comment by zmes50416** [comment]
Bug: TermFreq not count correctly in the map
see fb1e5efcecf6356f0723891962432f3138057515 for the unpass test case

**Comment by zmes50416** [comment]
Bug fix in (3015ffc)
